feature(offer page): create mobile & desktop offer components
GDSC-Lodz-University-of-Technology/warzywniax pull request #26
Opened 2023-03-21 20:22 UTC by miloszwierucki

2023-03-24 13:33 UTC, HKGx requested changes
Some issues, but the components look pretty neat. 👍

2023-03-24 13:33 UTC, HKGx commented on src/pages/OffersPage/OffersPage.tsx
> +  const [view, setView] = useState('list');
We probably should use an enum as "list" and "map" are 2 distinct states. 
```ts
enum OffersPageView {
  List,
  Map
}

export function OffersPage() {
  const [view, setView] = useState(OffersPageView.List);
  // more code here
}
```

2023-03-24 13:33 UTC, HKGx commented on src/pages/OffersPage/OffersPage.tsx
> +    if (handleView !== null) {
how can this be null?

2023-03-24 13:33 UTC, HKGx commented on src/pages/OffersPage/OffersPage.tsx
> +  //newView: string | null
why is this commented out?

2023-03-24 13:33 UTC, HKGx commented on src/pages/OffersPage/OffersPage.tsx
> +            value='list'
Let's use the previously mentioned enum for value

2023-03-24 13:33 UTC, HKGx commented on src/pages/OffersPage/OffersPage.tsx
> +            value='map'
Let's use the previously mentioned enum for value

2023-03-24 13:33 UTC, HKGx commented on src/pages/OffersPage/OffersPage.tsx
> +            <Typography component='span'>{t(' ­ Map')}</Typography>
`t(' Map')` is not defined in translations!

2023-03-24 13:33 UTC, HKGx commented on src/pages/OffersPage/components/Offer/Offer.tsx
> +            {`zł/${quantityUnit}`}
`zł` probably should be translated using i18n.
`zł` is natural for a Polish person, but in any English texts you'll encounter "PLN" instead

2023-03-24 13:33 UTC, HKGx commented on src/pages/OffersPage/components/Offer/Offer.tsx
> +        <GradientButton sx={{ width: 2 / 3 }}>Details</GradientButton>
translation?

2023-03-24 13:33 UTC, HKGx commented on src/pages/OffersPage/components/OfferList/OfferList.tsx
> +    setData((prevData) => [...prevData, ...response]);
NOTE: proper pagination would remove older elements so they won't be cluttering the memory, but it's not that needed here

2023-03-24 13:33 UTC, HKGx commented on src/pages/OffersPage/components/OfferList/OfferList.tsx
> +              key={index}
NOTE: 

> You might be tempted to use an item’s index in the array as its key. In fact, that’s what React will use if you don’t specify a key at all. But the order in which you render items will change over time if an item is inserted, deleted, or if the array gets reordered. Index as a key often leads to subtle and confusing bugs.
https://react.dev/learn/rendering-lists


When we start using firebase properly replace the `index` with UUID

2023-03-24 13:33 UTC, HKGx commented on src/templates/NavBar/NavBar.tsx
> +          {auth && <div>User</div>}
translation?

2023-03-24 13:33 UTC, HKGx commented on src/templates/NavBar/NavBar.tsx
> +            {auth ? 'Create an offer' : 'Log in'}
translation?

2023-03-24 13:33 UTC, HKGx commented on src/pages/OffersPage/OffersPage.tsx
> +        <Button sx={{ width: '50%' }}>Click for more</Button>
translation?

2023-03-24 13:33 UTC, HKGx commented on src/pages/OffersPage/components/Offer/Offer.tsx
> +      alt={`Photo of ${name}`}
translation? maybe

2023-03-24 13:33 UTC, HKGx commented on src/pages/OffersPage/components/OfferTags/OfferTags.tsx
> +    {categories.map((category) => (
here setting key to `category` is ok, because it's implied that categories are unique

2023-03-24 13:33 UTC, HKGx commented on src/templates/NavBar/NavBar.tsx
> +  const Scroll = () => {
camelCase!

2023-03-24 13:33 UTC, HKGx commented on src/templates/NavBar/NavBar.tsx
> +    const ScrollTop = window.pageYOffset;
camelCase!

2023-03-24 13:33 UTC, HKGx commented on src/templates/NavBar/NavBar.tsx
> +    if (ScrollTop > lastScrollTop && ScrollTop > 200) {
what's 200 in this context? the height of navbar?

2023-03-24 13:33 UTC, HKGx commented on src/templates/NavBar/NavBar.tsx
> +  let lastScrollTop = 0;
this probably should be a state
```ts
const [prevScrollPos, setPrevScrollPos] = useState(0);
```

2023-03-24 13:33 UTC, HKGx commented on src/templates/NavBar/NavBar.tsx
> +    }
```ts
const condition = ScrollTop > lastScrollTop && ScrollTop > 200
setShowBar(condition)
```

2023-03-24 18:24 UTC, miloszwierucki commented on src/pages/OffersPage/OffersPage.tsx
> +  const [view, setView] = useState('list');
Ok I'll correct it, we can also add a variable that can only take 2 values / (interface), will that be correct?

2023-03-24 18:42 UTC, miloszwierucki commented on src/pages/OffersPage/components/Offer/Offer.tsx
> +        <GradientButton sx={{ width: 2 / 3 }}>Details</GradientButton>
I'll add it

2023-03-24 18:54 UTC, miloszwierucki commented on src/templates/NavBar/NavBar.tsx
> +    if (ScrollTop > lastScrollTop && ScrollTop > 200) {
random number 😅, I wanted the bar not to be hidden right away, I can set it to half the height of the browser window

2023-03-25 23:00 UTC, HKGx requested changes
GitHub played me for an absolute fool and I thought that some conversations weren't fixed because it showed the first 4 commits, so I left probably 10+ random comments that aren't valid. 🙇 

I'll request a few changes but it's looking really promising 💪

2023-03-25 23:03 UTC, HKGx commented on src/pages/OffersPage/OffersPage.tsx
> +  const [view, setView] = useState('list');
I don't really understand what do you mean by "a variable that can only take 2 values", sorry. 🙏

2023-03-26 16:26 UTC, HKGx approved these changes
Looks good

2023-03-26 17:31 UTC, kaczor6418 requested changes
Almost good

2023-03-26 17:31 UTC, kaczor6418 commented on src/pages/OffersPage/components/OfferMap/OfferMap.tsx
> +export const OfferMap = () => <h2>Map</h2>;
use translation:
PL → Mapa
EN → Map

2023-03-26 17:31 UTC, kaczor6418 commented on src/pages/OffersPage/components/OfferTags/OfferTags.tsx
> +    ))}
`categorey` is a number, so it needs to be translated. Create separated Function/Map to get proper value for given number and use translation.

I would create a `Map<ProductCategory, string>` a common constant variable. You can create such a variable in `common/constants.ts`

2023-03-26 17:31 UTC, kaczor6418 commented on src/pages/OffersPage/components/OfferList/OfferList.tsx
> +                key={index}
once we start using our db as a source of data, we should use id instead of index

2023-03-26 22:42 UTC, miloszwierucki commented on src/pages/OffersPage/components/OfferMap/OfferMap.tsx
> +export const OfferMap = () => <h2>Map</h2>;
It's just temporary text

2023-03-26 22:53 UTC, miloszwierucki commented on src/pages/OffersPage/OffersPage.tsx
> +  const [view, setView] = useState('list');
I mean:
```
type typeView = 'map' | 'list';
const [view, setView] = useState('list') as [typeView, (view: typeView) => void];
```

2023-03-28 18:21 UTC, HKGx commented on src/pages/OffersPage/OffersPage.tsx
> +  const [view, setView] = useState('list');
useState is generic, so no need for `as`. 
also, that's what enums are for

2023-03-31 08:28 UTC, merged