Improve auth pages structure
GDSC-Lodz-University-of-Technology/warzywniax pull request #44
Opened 2023-04-01 11:26 UTC by mkidawa

closes: #43

2023-04-01 16:35 UTC, kaczor6418 requested changes

2023-04-01 16:35 UTC, kaczor6418 commented on src/pages/AuthPage/RegisterPage/components/RegisterForm/RegisterForm.tsx
> +};
can we move `RegisterFormProps` to *RegisterForm.types.ts* file?

2023-04-01 16:35 UTC, kaczor6418 commented on src/pages/AuthPage/LoginPage/components/SignInProvidersBox/SignInProvidersBox.tsx
> +};
can we move `SignInProvidersBoxProps` to *SignInProvidersBox.types.ts* file?

2023-04-01 16:35 UTC, kaczor6418 commented on src/pages/AuthPage/LoginPage/components/LoginForm/LoginForm.tsx
> +};
can we move `LoginFormProps` to *LoginForm.types.ts* file?

2023-04-01 16:37 UTC, kaczor6418 commented on src/pages/AuthPage/RegisterPage/components/RegisterForm/RegisterForm.tsx
> +};
just to follow structure described in docmentation:
https://github.com/GDSC-Lodz-University-of-Technology/warzywniax/wiki/Project-structure

2023-04-01 16:37 UTC, kaczor6418 commented on src/pages/AuthPage/LoginPage/components/SignInProvidersBox/SignInProvidersBox.tsx
> +};
just to follow structure described in docmentation:
https://github.com/GDSC-Lodz-University-of-Technology/warzywniax/wiki/Project-structure

2023-04-01 16:37 UTC, kaczor6418 commented on src/pages/AuthPage/LoginPage/components/LoginForm/LoginForm.tsx
> +};
just to follow the structure described in documentation:
https://github.com/GDSC-Lodz-University-of-Technology/warzywniax/wiki/Project-structure

2023-04-02 18:44 UTC, kaczor6418 approved these changes
LGTM :sunglasses:

2023-04-03 06:35 UTC, HKGx approved these changes
Looking good :+1:

2023-04-03 09:40 UTC, merged