chore(workflow) setup project
GDSC-Lodz-University-of-Technology/warzywniax pull request #8
Opened 2023-02-27 01:45 UTC by kaczor6418

closes #1

2023-02-28 12:17 UTC, HKGx requested changes
I commented mostly on ESLint rules that I think are unnecessary/bad.
I believe we should use https://github.com/trivago/prettier-plugin-sort-imports as it makes handling imports easier, but it can be added later 👍

2023-02-28 12:17 UTC, HKGx commented on src/main.tsx
> +import { ROUTER } from './router/router';
[*]

2023-02-28 12:17 UTC, HKGx commented on .eslintrc.json
> +    "@typescript-eslint/no-magic-numbers": "off",
magic numbers make it harder to comprehend code!!!

2023-02-28 12:17 UTC, HKGx commented on .eslintrc.json
> +    "@typescript-eslint/no-namespace": "off",
namespaces are pretty much outdated, we shouldn't disable this

2023-02-28 12:17 UTC, HKGx commented on .eslintrc.json
> +    "react/react-in-jsx-scope": "off"
[no-constant-binary-expression](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/react-in-jsx-scope.md#when-not-to-use-it)

> If you are using the [new JSX transform from React 17](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#removing-unused-react-imports), you should disable this rule by extending [react/jsx-runtime](https://github.com/jsx-eslint/eslint-plugin-react/blob/8cf47a8ac2242ee00ea36eac4b6ae51956ba4411/index.js#L165-L179) in your eslint config (add "plugin:react/jsx-runtime" to "extends").

2023-02-28 12:17 UTC, HKGx commented on .eslintrc.json
> +    "sort-keys": "off",
I like sorted keys but whatever

2023-02-28 12:17 UTC, HKGx commented on .eslintrc.json
> +    "no-use-before-define": "off",
what's wrong with this rule?

2023-02-28 16:54 UTC, kaczor6418 commented on .prettierrc.json
> +  "printWidth": 150,
I think for most modern screens this should be okay

2023-02-28 17:37 UTC, kaczor6418 commented on src/router/router.tsx
> +export const ROUTER = createBrowserRouter([rootRoute, offersRoute, shopsRoute]);
`router`

2023-02-28 17:40 UTC, kaczor6418 commented on .prettierrc.json
> +  "printWidth": 150,
`100`

2023-02-28 17:40 UTC, kaczor6418 commented on src/configs/mui.config.ts
> +export const CUSTOM_THEME = createTheme({
camelCase notation

2023-02-28 17:40 UTC, kaczor6418 commented on src/configs/firebase.config.ts
> +export const FIREBASE_CONNECTION = initializeApp({
camelCase notation

2023-02-28 17:40 UTC, kaczor6418 commented on src/router/offers.route.tsx
> +export const offersRoute: RouteObject = {
camelCase notation

2023-02-28 17:40 UTC, kaczor6418 commented on src/router/shops.route.tsx
> +export const shopsRoute: RouteObject = {
camelCase notation

2023-02-28 17:44 UTC, kaczor6418 commented on .eslintrc.json
> +    "import/no-default-export": "error",
let's keep this

2023-02-28 17:44 UTC, kaczor6418 commented on src/main.tsx
> +import { ROUTER } from './router/router';
camelCase notation

2023-02-28 17:47 UTC, kaczor6418 commented on .eslintrc.json
> +    "arrow-body-style": ["error", "always"],
as-needed

2023-02-28 17:55 UTC, kaczor6418 commented on .eslintrc.json
> +    "prefer-arrow-callback": "error",
this can stay

2023-02-28 17:56 UTC, kaczor6418 commented on .eslintrc.json
> +    "no-await-in-loop": "off",
let's turn it on

2023-02-28 17:59 UTC, kaczor6418 commented on .eslintrc.json
> +    "@typescript-eslint/no-magic-numbers": "off",
so lets keeps this as it is

2023-02-28 17:59 UTC, kaczor6418 commented on .eslintrc.json
> +    "@typescript-eslint/no-namespace": "off",
turn it on

2023-02-28 18:00 UTC, kaczor6418 commented on .eslintrc.json
> +    "react/react-in-jsx-scope": "off"
ok

2023-02-28 18:01 UTC, kaczor6418 commented on .eslintrc.json
> +    "sort-keys": "off",
turn it on

2023-02-28 18:04 UTC, kaczor6418 commented on .eslintrc.json
> +    "no-use-before-define": "off",
we are using typescript so this is not needed as TS doesn't allow use variable before declaration

2023-03-01 19:26 UTC, kaczor6418 commented on src/locales/i18n.ts
> +void i18n.use(initReactI18next).init({
to resolve unhandled promise (hack to satisfy TypeScript)

2023-03-01 20:20 UTC, mkidawa approved these changes
LGTM

2023-03-01 21:29 UTC, HKGx approved these changes
:+1:

2023-03-01 21:30 UTC, merged